-- ORDENA O ID POR ORDEM DECRESCENTE
SELECT * FROM users ORDER BY id DESC

-- ORDENA O ID POR ORDEM CRESCESCENTE
SELECT * FROM users ORDER BY ID ASC

-- ORDENA O first_name POR ORDEM DECRESCENTE (Z-A)
SELECT * FROM users ORDER BY first_name DESC

-- ORDENA O first_name POR ORDEM CRESCENTE (A-Z)
SELECT * FROM users ORDER BY first_name ASC